version: '3'

services:

  nginx:
    image: qq1007269259/nginx1:v1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf:/etc/nginx/conf.d
      - $PWD/html:/var/www/html
    links:
      - php:php
    depends_on:
      - php
    
    container_name: nginx

  php:
    image: qq1007269259/php-fpm8:v1
    ports:
      - "9000:9000"
    volumes:
      - $PWD/html:/var/www/html
      - $PWD/php/php.ini:/usr/local/etc/php/php.ini
      - $PWD/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql:mysql
      - redis:redis
    depends_on:
      - mysql
      - redis
    stdin_open: true
    container_name: php

  redis:
    image: qq1007269259/redis:v1
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/data:/data:rw
      - $PWD/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    container_name: redis

  mysql:
    image: qq1007269259/mysql8:v1
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql/conf:/etc/mysql/conf.d
      - $PWD/mysql/data:/var/lib/mysql
    container_name: mysql




